# https://github.com/gpakosz/.tmux

# List of plugins
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'ChanderG/tmux-notify'
set -g @tnotify-sleep-duration '1'
set -g @tnotify-verbose 'on'
# set-window-option -g mode-keys vi


set -g default-terminal "tmux-256color"
set -g history-limit 100000


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-h
bind-key C-h send-prefix


unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you
# want to use)
bind r source-file ~/.tmux.conf


setw -g automatic-rename on   # rename window to reflect current program
set -g status-interval 10     # redraw status line every 10 seconds

set -g monitor-activity on
set -g visual-activity on

setw -g mode-keys vi

# setw -g mode-keys vi
# setw -g mode-mouse on


# bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"


# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-n select-pane -t :.+
bind -n M-p select-pane -t :.-

bind -n M-Tab next-window  # select previous window
bind -n M-BTab previous-window # select next window

# split current window horizontally
bind -n M-2 split-window -v
# split current window vertically
bind -n M-3 split-window -h


# -- copy mode -----------------------------------------------------------------
bind -n M-y copy-mode
if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'

bind b list-buffers  # list paste buffers
bind p paste-buffer  # paste from the top paste buffer
bind P choose-buffer # choose which buffer to paste from
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# switch windows alt+number
bind-key -n M-& if-shell 'tmux select-window -t :0' '' 'new-window -t :0'
bind-key -n M-é if-shell 'tmux select-window -t :1' '' 'new-window -t :1'
bind-key -n 'M-"' if-shell 'tmux select-window -t :2' '' 'new-window -t :2'
bind-key -n "M-'" if-shell 'tmux select-window -t :3' '' 'new-window -t :3'
bind-key -n M-( if-shell 'tmux select-window -t :4' '' 'new-window -t :4'
bind-key -n M-§ if-shell 'tmux select-window -t :5' '' 'new-window -t :5'
bind-key -n M-è if-shell 'tmux select-window -t :6' '' 'new-window -t :6'
bind-key -n M-! if-shell 'tmux select-window -t :7' '' 'new-window -t :7'
bind-key -n M-ç if-shell 'tmux select-window -t :8' '' 'new-window -t :8'
bind-key -n M-à if-shell 'tmux select-window -t :9' '' 'new-window -t :9'

# Prefix + number
bind-key & if-shell 'tmux select-window -t :0' '' 'new-window -t :0'
bind-key é if-shell 'tmux select-window -t :1' '' 'new-window -t :1'
bind-key '"' if-shell 'tmux select-window -t :2' '' 'new-window -t :2'
bind-key "'" if-shell 'tmux select-window -t :3' '' 'new-window -t :3'
bind-key ( if-shell 'tmux select-window -t :4' '' 'new-window -t :4'
bind-key § if-shell 'tmux select-window -t :5' '' 'new-window -t :5'
bind-key è if-shell 'tmux select-window -t :6' '' 'new-window -t :6'
bind-key ! if-shell 'tmux select-window -t :7' '' 'new-window -t :7'
bind-key ç if-shell 'tmux select-window -t :8' '' 'new-window -t :8'
bind-key à if-shell 'tmux select-window -t :9' '' 'new-window -t :9'


run -b '~/.tmux/plugins/tpm/tpm'
